const alertkey = {
   //PRODUCT KEY
   C_PRODUCT_ALERT: 'C_PRODUCT_ALERT',
   D_PRODUCT_ALERT: 'D_PRODUCT_ALERT',
   U_PRODUCT_ALERT: 'U_PRODUCT_ALERT',

   //CATEGORY KEY
   C_CATEGORY_ALERT: 'C_CATEGORY_ALERT',
   D_CATEGORY_ALERT: 'D_CATEGORY_ALERT',
   U_CATEGORY_ALERT: 'U_CATEGORY_ALERT',
   //SUB CATEGORY
   D_SUBCATEGORY_ALERT: 'D_SUBCATEGORY_ALERT',

   //SUB CATEGORY KEY
   C_SUB_CATEGORY_ALERT: 'C_SUB_CATEGORY_ALERT',
   D_SUB_CATEGORY_ALERT: 'D_SUB_CATEGORY_ALERT',
   U_SUB_CATEGORY_ALERT: 'U_SUB_CATEGORY_ALERT',

   //STOCK
   C_STOCK_ALERT: 'C_STOCK_ALERT',
   //INVOICE
   C_INVOICE_ALERT: 'C_INVOICE_ALERT',
   //CUSTOMER
   C_CUSTOMER_ALERT: 'C_CUSTOMER_ALERT',
   D_CUSTOMER_ALERT: 'D_CUSTOMER_ALERT',
   U_CUSTOMER_ALERT: 'U_CUSTOMER_ALERT',

   //PAYMENT
   C_PAYMENT_ALERT: 'C_PAYMENT_ALERT',
   //LOCATION
   C_LOCATION_ALERT: 'C_LOCATION_ALERT',
   D_LOCATION_ALERT: 'D_LOCATION_ALERT',
   U_LOCATION_ALERT: 'U_LOCATION_ALERT',

   //ACCESS DENIED
   ACCESS_DENIED_ALERT: 'ACCESS_DENIED_ALERT',
   //DisplayCommonError
   DISPLAY_COMMON_ERROR: 'DISPLAY_COMMON_ERROR',

   //USER KEY
   C_USER_ALERT: 'C_USER_ALERT',
   D_USER_ALERT: 'D_USER_ALERT',
   U_USER_ALERT: 'U_USER_ALERT',
   //AUTH
   AUTH_LOGIN_ALERT: 'AUTH_LOGIN_ALERT',
};

export { alertkey };
