const alertkey = {
   //PRODUCT KEY
   C_PRODUCT_ALERT: 'C_PRODUCT_ALERT',
   D_PRODUCT_ALERT: 'D_PRODUCT_ALERT',
   U_PRODUCT_ALERT: 'U_PRODUCT_ALERT',

   //CATEGORY KEY
   C_CATEGORY_ALERT: 'C_CATEGORY_ALERT',
   D_CATEGORY_ALERT: 'D_CATEGORY_ALERT',
   U_CATEGORY_ALERT: 'U_CATEGORY_ALERT',

   //SUB CATEGORY KEY
   C_SUB_CATEGORY_ALERT: 'C_SUB_CATEGORY_ALERT',
   D_SUB_CATEGORY_ALERT: 'D_SUB_CATEGORY_ALERT',
   U_SUB_CATEGORY_ALERT: 'U_SUB_CATEGORY_ALERT',

   //STOCK
   C_STOCK_ALERT: 'C_STOCK_ALERT',
   //INVOICE
   C_INVOICE_ALERT: 'C_INVOICE_ALERT',
   //CUSTOMER
   C_CUSTOMER_ALERT: 'C_CUSTOMER_ALERT',
   //PAYMENT
   C_PAYMENT_ALERT: 'C_PAYMENT_ALERT',
};

export { alertkey };
