const popupkey = {
   //PRODUCT KEY
   C_PRODUCT: 'C_PRODUCT',
   D_PRODUCT: 'D_PRODUCT',
   U_PRODUCT: 'U_PRODUCT',
   PRODUCT_ACCESS_DENIED: 'PRODUCT_ACCESS_DENIED',
   //CATEGORY KEY
   C_CATEGORY: 'C_CATEGORY',
   U_CATEGORY: 'U_CATEGORY',
   D_CATEGORY: 'D_CATEGORY',
   CATEGORY_ACCESS_DENIED: 'CATEGORY_ACCESS_DENIED',
   //SUB CATEGORY
   D_SUBCATEGORY: 'D_SUBCATEGORY',
   //STOCK
   C_STOCK: 'C_STOCK',
   STOCK_IN_ACCESS_DENIED: 'STOCK_IN_ACCESS_DENIED',
   STOCK_OUT_ACCESS_DENIED: 'STOCK_OUT_ACCESS_DENIED',
   //INVOICE
   V_INVOICE_PAYMENT: 'V_INVOICE_PAYMENT',
   V_INVOICE_INFO: 'V_INVOICE_INFO',
   V_CUSTOMER_FILTER_DATA: 'V_CUSTOMER_FILTER_DATA',
   ADD_INVOICE_PAYMENT: 'ADD_INVOICE_PAYMENT',
   PAYMENT_WINDOW: 'PAYMENT_WINDOW',
   V_SALESREF_FILTER_DATA: 'V_SALESREF_FILTER_DATA',
   INVOICE_ACCESS_DENIED: 'INVOICE_ACCESS_DENIED',
   //CUSTOMER
   C_CUSTOMER: 'C_CUSTOMER',
   D_CUSTOMER: 'D_CUSTOMER',
   U_CUSTOMER: 'U_CUSTOMER',
   CUSTOMER_ACCESS_DENIED: 'CUSTOMER_ACCESS_DENIED',
   //LOCATION
   C_LOCATION: 'C_LOCATION',
   D_LOCATION: 'D_LOCATION',
   U_LOCATION: 'U_LOCATION',
   LOCATION_ACCESS_DENIED: 'LOCATION_ACCESS_DENIED',
   //ACCESS DENIED
   ACCESS_DENIED: 'ACCESS_DENIED',
   //PAYMENT
   PAYMENT_ACCESS_DENIED: 'PAYMENT_ACCESS_DENIED',
   //USER
   C_USER: 'C_USER',
   D_USER: 'D_USER',
   U_USER: 'U_USER',
   USER_ACCESS_DENIED: 'USER_ACCESS_DENIED',

   //COMMON ACCESS DENIED
   COMMON_ACCESS_DENIED: 'COMMON_ACCESS_DENIED',
};

export { popupkey };
