const popupkey = {
   //PRODUCT KEY
   C_PRODUCT: 'C_PRODUCT',
   D_PRODUCT: 'D_PRODUCT',
   U_PRODUCT: 'U_PRODUCT',
   //CATEGORY KEY
   C_CATEGORY: 'C_CATEGORY',
   U_CATEGORY: 'U_CATEGORY',
   D_CATEGORY: 'D_CATEGORY',
   //SUB CATEGORY
   D_SUBCATEGORY: 'D_SUBCATEGORY',
   //STOCK
   C_STOCK: 'C_STOCK',
   //INVOICE
   V_INVOICE_PAYMENT: 'V_INVOICE_PAYMENT',
   V_INVOICE_INFO: 'V_INVOICE_INFO',
   V_CUSTOMER_FILTER_DATA: 'V_CUSTOMER_FILTER_DATA',
   ADD_INVOICE_PAYMENT: 'ADD_INVOICE_PAYMENT',
   PAYMENT_WINDOW: 'PAYMENT_WINDOW',
   V_SALESREF_FILTER_DATA: 'V_SALESREF_FILTER_DATA',
   //CUSTOMER
   C_CUSTOMER: 'C_CUSTOMER',
   D_CUSTOMER: 'D_CUSTOMER',
   //LOCATION
   C_LOCATION: 'C_LOCATION',
   D_LOCATION: 'D_LOCATION',
};

export { popupkey };
