const type = {
   OPEN_CLOSE_PRODUCT_POPUP: 'OPEN_CLOSE_PRODUCT_POPUP',
   SHOW_POPUP: 'SHOW_POPUP',
   HIDE_POPUP: 'HIDE_POPUP',
   SHOW_ALERT: 'SHOW_ALERT',
   HIDE_ALERT: 'HIDE_ALERT',
   SHOW_SIDE_NAV: 'SHOW_SIDE_NAV',
   HIDE_SIDE_NAV: 'HIDE_SIDE_NAV',
   TOGGLE_SIDE_NAV: 'TOGGLE_SIDE_NAV',
   STORE_PRODUCT: 'STORE_PRODUCT',
   UPDATE_PRODUCT: 'UPDATE_PRODUCT',
   DELETE_PRODUCT: 'DELETE_PRODUCT',
   STORE_CATEGORY: 'STORE_CATEGORY',
   //LOADER
   SHOW_LOADER: 'SHOW_LOADER',
   HIDE_LOADER: 'HIDE_LOADER',
   //LOCATION
   STORE_LOCATION: 'STORE_LOCATION',
   //UNIT
   STORE_UNIT: 'STORE_UNIT',
   //STOCK
   STORE_STOCK_IN: 'STORE_STOCK_IN',
   STORE_STOCK_OUT: 'STORE_STOCK_OUT',
   //CUSTOMER
   STORE_CUSTOMER: 'STORE_CUSTOMER',

   //INVOICE
   STORE_INVOICE: 'STORE_INVOICE',
   STORE_INVOICE_CUSTOMERS: 'STORE_INVOICE_CUSTOMERS',
   STORE_INVOICE_CUSTOMER_INFO: 'STORE_INVOICE_CUSTOMER_INFO',
   STORE_INVOICE_DATE: 'STORE_INVOICE_DATE',
   STORE_INVOICE_ITEM: 'STORE_INVOICE_ITEM',
   SET_FILTER_INVOICE_DATA: 'SET_FILTER_INVOICE_DATA',
   STORE_INVOICE_DISCOUNT: 'STORE_INVOICE_DISCOUNT',
   CALCULATE_INVOICE_AMOUNTS: 'CALCULATE_INVOICE_AMOUNTS',
   RESET_INVOICE: 'RESET_INVOICE',
   STORE_PAYMENT_STATUS: 'STORE_PAYMENT_STATUS',
   STORE_INVOICE_REMARK: 'STORE_INVOICE_REMARK',
   ADD_NEW_INVOICE_ITEM: 'ADD_NEW_INVOICE_ITEM',
   REMOVE_INVOICE_ITEM: 'REMOVE_INVOICE_ITEM',
   STORE_INVOICE_PAYMENT: 'STORE_INVOICE_PAYMENT',
   REMOVE_INVOICE_PAYMENT: 'REMOVE_INVOICE_PAYMENT',
   STORE_NEXT_INVOICE_NO: 'STORE_NEXT_INVOICE_NO',
   STORE_SALES_REF: 'STORE_SALES_REF',
   STORE_FETCH_SALES_REF: 'STORE_FETCH_SALES_REF',
   //DELIVERY MODE
   STORE_DELIVERYMODE: 'STORE_DELIVERYMODE',
   //SUPPLIER
   STORE_SUPPLIER_CODE: 'STORE_SUPPLIER_CODE',
   //RECEIVER
   STORE_RECEIVER_CODE: 'STORE_RECEIVER_CODE',
   //PAYMENTS
   STORE_PAYMENT: 'STORE_PAYMENT',

   //PRODUCT
   STORE_NEXT_BARCODE: 'STORE_NEXT_BARCODE',
};
export default type;
